### PR TITLE
feat: add startup options to main macro

### LINKED ISSUE #97: Allow disabling banner when using `vexide` crate.
## What's the motivation for this feature?
Programs that need complete control over serial output cannot currently use the `vexide` crate because of the inconfigurable banner.

## Describe the solution you'd like
The `vexide::main` macro should have an option to disable the banner and the feature on `vexide_startup` for disabling it should be removed. This would be a more user-friendly way than having to disable `vexide`'s default features.

```rs
#[vexide::main] // banner = true
async fn main(p: Peripherals) {}

#[vexide::main(banner = false)]
async fn main(p: Peripherals) {}

#[vexide::main(banner = true)]
async fn main(p: Peripherals) {}
```

## Describe the drawbacks, if any
This would be a breaking change.

## Describe the alternative solutions, if any
The alternative would be to add a `banner` feature to `vexide`. This would have the unintended consequence of disabling the banner for anyone using `default-features = false`.

## Additional context
I would be willing to implement this feature.

### PR DESCRIPTION
**Pull request by doinkythederp**
## Describe the changes this PR makes. Why should it be merged?

This PR moves the option for toggling the vexide ASCII art banner into the parameters of the main macro to make it easier to disable. It fixes #97. It also adds a way to use a custom code signature.

This likely does not come at a code size cost compared to disabling the banner with the feature because it uses const generics to toggle the banner, but I haven't gotten to profiling yet.

## Additional Context
- These are breaking changes (semver: major).
- I have tested these changes on a VEX V5 brain.
- These changes update the crate's interface (e.g. functions/modules added or changed).

### CODE REVIEW

**Comment by doinkythederp** [comment]
`bannerless.bin` is 0.692 kilobytes smaller than `basic.bin` in release mode.

**Review by Tropix126 — APPROVED** [review]
LGTM The only thing im not totally sure is whether or not the `code_sig` option should be shortened to that (rather than `code_signature`), but thats a bikeshed thing that can come later.

**Review by Tropix126 — CHANGES_REQUESTED** [review]
Actually, I take that back. AFAIK the old feature flags are still present in the crate manifests, so those should be removed.

**Comment by doinkythederp** [comment]
> Actually, I take that back. AFAIK the old feature flags are still present in the crate manifests, so those should be removed.

Good catch

**Comment by doinkythederp** [comment]
BTW it looks like the Check and Test failures aren't caused by this PR and were merely revealed by me making the CI stricter

**Review by Gavin-Niederman — APPROVED** [review]
LGTM (LiGht Theme Mode)

**Pull request merged**
