### PR TITLE
fix: libm, time documentation

### PR DESCRIPTION
**Pull request by Tropix126**
## Describe the changes this PR makes. Why should it be merged?
This PR is a bit all over the place, but it fixes two simple things:
- Switches to the `softfp` build of libm rather than the `hard` version, since that was causing trouble with some math functions just not working (likely due to ABI incompatibility).
- Fixes the documentation example of one of the `Instant` methods, since that wasn't copied from the standard library correctly. Some examples also still used an ancient pros-rs era `use`.

### CODE REVIEW

**Comment by Tropix126** [comment]
Fixes #93.

**Review by doinkythederp — CHANGES_REQUESTED** [review]
This seems to work as intended, but the source code of the compiled libm should be linked in the float module. We might also consider using a Rust-based alternative.

The blog release post for vexide says, "Every single line of code in vexide is open source and 100% Rust." I would consider anything we require users to link to as a "line of code in vexide," so adding in a C library with unspecified source code seems to stretch this claim.

**Comment by Tropix126** [comment]
> This seems to work as intended, but the source code of the compiled libm should be linked in the float module. We might also consider using a Rust-based alternative.

Yeah, will do.

> This seems to work as intended, but the source code of the compiled libm should be linked in the float module. We might also consider using a Rust-based alternative.

> The blog release post for vexide says, "Every single line of code in vexide is open source and 100% Rust." I would consider anything we require users to link to as a "line of code in vexide," so adding in a C library with unspecified source code seems to stretch this claim.

I agree with this sentiment, and i'll probably make an optional feature for using the rust libm instead. Currently I care more about functionality over everything being in rust though, and the rust libm port both performs significantly worse and results in larger binaries (on the order of 15kb larger).

**Comment by Tropix126** [comment]
I've added a disclaimer to the top of the `vexos.rs` file. The feature flag can come in a later PR, since that'd require more substantial changes and this is just intended as a quick fix to get math working at all.

**Pull request merged**
