### PR TITLE
refactor: use workspace.dependencies for shared dependencies

### PR DESCRIPTION
**Pull request by Gavin-Niederman**
## Describe the changes this PR makes. Why should it be merged?
This PR moves dependencies shared between multiple vexide crates into the workspace. This makes it easier to update shared dependencies.
## Additional Context
- I have tested these changes on a VEX V5 brain.
- These are *only* non-code changes (e.g. documentation, README.md).

### CODE REVIEW

**Review by doinkythederp — COMMENTED** [review]
I would consider running a formatter

**Review by doinkythederp — COMMENTED** [review]
Are we OK with these changes making `cargo add` unusable in this repo?
<https://github.com/rust-lang/cargo/issues/10608>

**Comment by Gavin-Niederman** [comment]
This doesn't make cargo ads unusable. That issue is just referring to how cargo adding a dependency that is in the workspace dependencies automatically adds it as that workspace dependency.

**Comment by doinkythederp** [comment]
Oops, I think I must have misinterpreted that cargo issue.

**Review by doinkythederp — APPROVED** [review]

**Pull request merged**
