### PR TITLE
feat: add exit status to Termination

### PR DESCRIPTION
**Pull request by doinkythederp**
## Describe the changes this PR makes. Why should it be merged?

This PR adds an `ExitStatus` enum which is returned by `Termination` to represent whether the program was successful, similar to how the standard library's `Termination` returns an `ExitStatus` struct. This would make it easier to implement unit testing because the runner can decide if a test was successful or a failure based on the output of `Termination::report`, like how the builtin `test` crate does.

## Additional Context
- I have tested these changes on a VEX V5 brain.
- These are breaking changes (semver: major).
- These changes update the crate's interface (e.g. functions/modules added or changed).

### CODE REVIEW

**Review by Gavin-Niederman — COMMENTED** [review]
I fundamentally disagree with this change. Exit codes are a feature of many operating systems, which is why the Rust standard library supports them, but VEXos doesn't so exit codes are completely meaningless.

**Comment by doinkythederp** [comment]
> I fundamentally disagree with this change. Exit codes are a feature of many operating systems, which is why the Rust standard library supports them, but VEXos doesn't so exit codes here are completely meaningless.

ExitCode is useful to vexide because if Termination returns some sort of indicator of success or failure without exiting the program, a unit test runner could decide whether a test (which is essentially a mini-program) succeeded or failed. I chose to use an ExitCode enum with a success and failure variants to make the API more familiar to users of `std`, but `Result<(), ()>` would work too (although it triggers a clippy lint).

**Comment by Gavin-Niederman** [comment]
> but Result<(), ()> would work too (although it triggers a clippy lint).

Why not make an enum with a success and failure variant and implement `Termination` for it instead of adding anything to vexide?
You can easily do something like this for tests:
```rust
enum TestResult {
   Success,
   Failure
}
impl vexide::core::program::Termination for TestResult {
    fn report(self) {
        match self {
            Self::Success => println!("Test succeeded!"),
            Self::Failure => println!("Test failed horribly!")
        }
    }
}

fn main() -> TestResult {
    TestResult::Failure
}
```

**Comment by doinkythederp** [comment]
> > but Result<(), ()> would work too (although it triggers a clippy lint).
> 
> Why not make an enum with a success and failure variant and implement `Termination` for it instead of adding anything to vexide? You can easily do something like this for tests:
> 
> ```rust
> enum TestResult {
>    Success,
>    Failure
> }
> impl vexide::core::program::Termination for TestResult {
>     fn report(self) {
>         match self {
>             Self::Success => println!("Test succeeded!"),
>             Self::Failure => println!("Test failed horribly!")
>         }
>     }
> }
> 
> fn main() -> TestResult {
>     TestResult::Failure
> }
> ```

For context, in Rust unit testing, a test program can return any type implementing Termination; the return value of `Termination::report` is then used to decide whether the test was successful. The `test` crate uses this in a fashion similar to the following:

```rs
// Rust `test` crate pseudocode

#[test]
fn my_test() -> impl Termination {
    std::fs::read_to_string("file.txt")?;
    Ok(())
}

// test runner
fn main() {
    let code = catch_unwind(|| Termination::report(my_test()));
    if is_success(code) {
        println!("my_test: success");
    } else {
        println!("my_test: failure");
    }
}
```

Simply implementing vexide's Termination for a custom type like TestResult does not solve the problem of test runners not being able to tell the success or failure of a test. Because tests are allowed to return anything that satisfies `impl Termination`, they could return, say an `Err` Result, and the test runner would not be able to handle it. The changes made in this pull request where vexide's Termination returns a indicator of success or failure allow any type that implements Termination to be used to decide whether a test was successful, similarly to how any type that implements Termiantion can already be used to decide whether `main` was successful.

If these changes are not merged, a test runner would either have to:

1. Implement their own library-specific Termination trait that has an indicator of success or failure, which does not make sense because it would effectively do the same thing as vexide's Termination (decide whether a value represents a success or failure, and print a failure if neccesary)
2. Require tests to return a type like Result<(), Box<dyn Error>> which is less ergonomic
3. Require tests to return a type like TestResult which objectively worse because it has less information about why the test failed.

**Comment by Gavin-Niederman** [comment]
Requiring tests to return a result is the best option.

**Pull request closed without merging**
