### PR TITLE
feat: add metadata to errors

### PR DESCRIPTION
**Pull request by doinkythederp**
## Describe the changes this PR makes. Why should it be merged?

Adds metadata to errors to make their error messages more useful.

Before:

```
No device is plugged into the port.
```

After:

```
Expected a device to be connected to port 14
```

Also, replaces `#[snafu(display("{source}"), context(false))]` with `#[snafu(transparent)]` and adds usage of snafu's built in `ensure` macro for error checking.

Error messages open for tweaking!

## Additional Context
- These are breaking changes (semver: major).

### CODE REVIEW

**Review by Tropix126 — APPROVED** [review]
LGTM

**Comment by Tropix126** [comment]
Actually, you should probably update the changelog. Doesn't need to be anything specific, just broadly mention the refactor existing.

**Comment by doinkythederp** [comment]
> Actually, you should probably update the changelog. Doesn't need to be anything specific, just broadly mention the refactor existing.

See https://github.com/vexide/vexide/pull/221/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed

**Comment by Tropix126** [comment]
Whoops, LGTM.

**Pull request merged**
