### PR TITLE
refactor: update linkerscript

### PR DESCRIPTION
**Pull request by Tropix126**
## Describe the changes this PR makes. Why should it be merged?
- Use `rodata`/`data` rather than `rodata1`/`data`.
- Correctly place `.ARM.extab` section.
- Move `.code_signature` to its own section outside of `.text`.

### CODE REVIEW

**Comment by doinkythederp** [comment]
Do we know what `.ARM.extab` is used for? I can't find any info online.

**Comment by Tropix126** [comment]
> Do we know what `.ARM.extab` is used for? I can't find any info online.

Not entirely sure myself. From what little pieces I can get from the ARM docs, it's just additional information for stack unwinding. Placing it is required for `.code_signature` to be its own section separate from `.text`, though.

image

**Review by Gavin-Niederman — CHANGES_REQUESTED** [review]

**Review by Gavin-Niederman — APPROVED** [review]
LGTM (assuming its tested)

**Comment by Gavin-Niederman** [comment]
just tested and it works fine so im merging

**Pull request merged**
